# Generated by Django 4.2 on 2026-05-13 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="分类名称"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="分类描述"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="fas fa-tag",
                        max_length=50,
                        verbose_name="图标CSS类",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "道具分类",
                "verbose_name_plural": "道具分类",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="道具名称")),
                (
                    "game",
                    models.CharField(
                        choices=[
                            ("lol", "英雄联盟"),
                            ("csgo", "CS:GO"),
                            ("dota2", "Dota 2"),
                            ("genshin", "原神"),
                            ("pubg", "PUBG"),
                            ("valorant", "Valorant"),
                            ("wow", "魔兽世界"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="所属游戏",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="价格"
                    ),
                ),
                ("description", models.TextField(verbose_name="描述")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="items/",
                        verbose_name="道具图片",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "在售"),
                            ("sold", "已售出"),
                            ("off_shelf", "已下架"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, verbose_name="浏览次数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发布时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="items.category",
                        verbose_name="分类",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="卖家",
                    ),
                ),
            ],
            options={
                "verbose_name": "游戏道具",
                "verbose_name_plural": "游戏道具",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="收藏时间"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="items.item",
                        verbose_name="道具",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "收藏",
                "verbose_name_plural": "收藏",
                "ordering": ["-created_at"],
                "unique_together": {("user", "item")},
            },
        ),
    ]
