# Generated by Django 4.2 on 2026-05-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="stock",
            field=models.PositiveIntegerField(default=1, verbose_name="库存"),
        ),
        migrations.AlterField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "在售"),
                    ("locked", "已锁定"),
                    ("sold", "已售出"),
                    ("off_shelf", "已下架"),
                ],
                default="available",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
