# Generated by Django 4.2 on 2026-06-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0002_rechargerequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="rechargerequest",
            name="out_trade_no",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                unique=True,
                verbose_name="商户订单号",
            ),
        ),
        migrations.AddField(
            model_name="rechargerequest",
            name="trade_no",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="支付宝交易号"
            ),
        ),
    ]
