# Generated by Django 4.2 on 2026-05-27 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_no",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="支付单号"
                    ),
                ),
                (
                    "pay_method",
                    models.CharField(
                        default="mock", max_length=20, verbose_name="支付方式"
                    ),
                ),
                (
                    "pay_status",
                    models.CharField(
                        choices=[
                            ("pending", "待支付"),
                            ("success", "支付成功"),
                            ("failed", "支付失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="支付状态",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="支付金额",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="orders.order",
                        verbose_name="订单",
                    ),
                ),
            ],
            options={
                "verbose_name": "支付记录",
                "verbose_name_plural": "支付记录",
                "ordering": ["-created_at"],
            },
        ),
    ]
